export enum HttpStatus {
  /** 状态征程, 客户端可以继续请求 */
  CONTINUE = 100,
  /** 服务器已切换协议 */
  SWITCHING_PROTOCOLS = 101,
  /** @deprecated 服务器已接受请求 */
  PROCESSING = 102,
  /** 服务器还在响应数据 */
  EARLY_HINTS = 103,
  /** 请求成功 */
  OK = 200,
  /** 创建成功 */
  CREATED = 201,
  /** 服务器已接受请求 */
  ACCEPTED = 202,
  /** 请求已经成功被响应, 但负载被代理服务器修改 */
  NON_AUTHORITATIVE_INFORMATION = 203,
  /** 服务器已完成响应, 但客户端不需要离开当前页面 */
  NO_CONTENT = 204,
  RESET_CONTENT = 205,
  PARTIAL_CONTENT = 206,
  MULTI_STATUS = 207,
  ALREADY_REPORTED = 208,
  IM_USED = 226,
  MULTIPLE_CHOICES = 300,
  MOVED_PERMANENTLY = 301,
  FOUND = 302,
  SEE_OTHER = 303,
  NOT_MODIFIED = 304,
  USE_PROXY = 305,
  UNUSED = 306,
  TEMPORARY_REDIRECT = 307,
  PERMANENT_REDIRECT = 308,
  BAD_REQUEST = 400,
  /** 客户端错误, 缺乏身份验证凭证 */
  UNAUTHORIZED = 401,
  PAYMENT_REQUIRED = 402,
  /** 客户端错误, 需要授权访问 */
  FORBIDDEN = 403,
  /** 客户端请求的资源不存在 */
  NOT_FOUND = 404,
  METHOD_NOT_ALLOWED = 405,
  NOT_ACCEPTABLE = 406,
  PROXY_AUTHENTICATION_REQUIRED = 407,
  REQUEST_TIMEOUT = 408,
  CONFLICT = 409,
  GONE = 410,
  LENGTH_REQUIRED = 411,
  PRECONDITION_FAILED = 412,
  PAYLOAD_TOO_LARGE = 413,
  URI_TOO_LONG = 414,
  UNSUPPORTED_MEDIA_TYPE = 415,
  RANGE_NOT_SATISFIABLE = 416,
  EXPECTATION_FAILED = 417,
  IM_A_TEAPOT = 418,
  MISDIRECTED_REQUEST = 421,
  UNPROCESSABLE_ENTITY = 422,
  LOCKED = 423,
  FAILED_DEPENDENCY = 424,
  TOO_EARLY = 425,
  UPGRADE_REQUIRED = 426,
  PRECONDITION_REQUIRED = 428,
  /** 客户端请求过于频繁 */
  TOO_MANY_REQUESTS = 429,
  REQUEST_HEADER_FIELDS_TOO_LARGE = 431,
  UNAVAILABLE_FOR_LEGAL_REASONS = 451,
  /** 服务器内部错误 */
  INTERNAL_SERVER_ERROR = 500,
  /** 服务器不支持请求的功能 */
  NOT_IMPLEMENTED = 501,
  /** 网关错误 */
  BAD_GATEWAY = 502,
  /** 服务不可用 */
  SERVICE_UNAVAILABLE = 503,
  /** 网关超时 */
  GATEWAY_TIMEOUT = 504,
  /** HTTP 版本不受支持 */
  HTTP_VERSION_NOT_SUPPORTED = 505,
  /** 服务器不支持请求的变体 */
  VARIANT_ALSO_NEGOTIATES = 506,
  /** 服务器不能存储相关内容 */
  INSUFFICIENT_STORAGE = 507,
  /** 服务器中断一个操作 */
  LOOP_DETECTED = 508,
  /** 不支持请求的扩展声明 */
  NOT_EXTENDED = 510,
  /** 客户端网络未认证 */
  NETWORK_AUTHENTICATION_REQUIRED = 511,
}
